// そだてて！プラントアニマルズ 収録樹種データ（初期10種）
// 出典: harunami-plant-base 図鑑 spec-table / 庭木キャラ図鑑_動物マッピング / 年間投稿割り当て
const SPECIES = [
  {
    name: "サクラ", animal: "ウグイス", type: "flower",
    bloomColor: ["#f6bfd0", "#fde9f0"],
    evergreen: false, height: "tall",
    hintLeaf: "先がとがって、縁に細かいギザギザのある葉っぱ",
    hintBloom: "淡いピンクの花が咲きそうな気配…",
    seasonMonths: [4],
    matureDesc: "春、いっせいに咲いてぱっと散っていく花の代表。この木の下でお花見をするのが日本の春の楽しみです。",
    doneText: "花がさいた！",
    appeal: "春の訪れを告げる美しい花。日本の文化と深く結びついた、いわずと知れた春の主役です。",
  },
  {
    name: "ウメ", animal: "メジロ", type: "flower",
    bloomColor: ["#f2aebd", "#fdf3f5"],
    evergreen: false, height: "medium",
    hintLeaf: "卵形の葉っぱで、縁に細かいギザギザ",
    hintBloom: "香りのよい花が咲きそうな気配…",
    seasonMonths: [2],
    matureDesc: "まだ寒い早春に、香りのよい花をどの木よりも早く咲かせます。実は梅干しや梅酒に使われます。",
    doneText: "花がさいた！",
    appeal: "春の訪れを告げる花として古くから親しまれ、梅干しや梅酒など実用の価値も高い木です。",
  },
  {
    name: "アジサイ", animal: "カタツムリ", type: "flower",
    bloomColor: ["#8ea6e6", "#b79ce0"],
    evergreen: false, height: "small",
    hintLeaf: "つやのある大きめの葉っぱ、縁にギザギザ",
    hintBloom: "青や紫の花が咲きそうな気配…",
    seasonMonths: [6],
    matureDesc: "雨の季節がいちばん似合う木。土の酸性度によって花の色が変わる、ふしぎな性質を持っています。",
    doneText: "花がさいた！",
    appeal: "梅雨どきに美しい花を咲かせます。土の酸性度で花色が変わり、多様な花色と咲き方が魅力です。",
  },
  {
    name: "ムクゲ", animal: "インコ", type: "flower",
    bloomColor: ["#e6a5c4", "#f5e1ec"],
    evergreen: false, height: "small",
    hintLeaf: "浅く3つに切れこむ、ひし形っぽい葉っぱ",
    hintBloom: "大きな花が咲きそうな気配…",
    seasonMonths: [7],
    matureDesc: "ひとつの花はたった一日でしぼみますが、次々に咲き継いで夏のあいだずっと花を見せてくれます。",
    doneText: "花がさいた！",
    appeal: "ひとつの花は一日でしぼむのに、次々と咲き継いで夏から秋まで長く楽しめる、丈夫な花木です。",
  },
  {
    name: "サルスベリ", animal: "サル", type: "flower",
    bloomColor: ["#ef86ad", "#fbdce7"],
    evergreen: false, height: "tall",
    hintLeaf: "丸みのある小さめの葉っぱ。幹がつるつる…？",
    hintBloom: "フリルみたいな花が咲きそうな気配…",
    seasonMonths: [8],
    matureDesc: "100日咲き続けるといわれるほど花期が長い夏の木。幹はつるつるで、木のぼり上手な動物でもすべりそう。",
    doneText: "花がさいた！",
    appeal: "百日紅の名のとおり長い期間花を楽しめます。猿もすべるといわれる、なめらかな幹肌が特徴です。",
  },
  {
    name: "キンモクセイ", animal: "ミツバチ", type: "flower",
    bloomColor: ["#f5a93b", "#fbe3b8"],
    evergreen: true, height: "medium",
    hintLeaf: "濃い緑でつやのある、かたい葉っぱ",
    hintBloom: "なんだか甘い香りがしてきそう…",
    seasonMonths: [9],
    matureDesc: "秋になると、姿より先に甘い香りでそこにあると気づく木。小さなオレンジ色の花が枝いっぱいに咲きます。",
    doneText: "花がさいた！",
    appeal: "甘く芳醇な香りで秋の訪れを告げる風物詩。小さなオレンジ色の花が枝いっぱいに咲きます。",
  },
  {
    name: "カキ", animal: "タヌキ", type: "fruit",
    bloomColor: ["#ef8a3c", "#fbd9b8"],
    evergreen: false, height: "medium",
    hintLeaf: "大きめの卵形の葉っぱ、縁に細かいギザギザ",
    hintBloom: "オレンジ色の実がなりそうな気配…",
    seasonMonths: [10],
    matureDesc: "秋にオレンジ色の実がたくさんなる、日本の里の風景でおなじみの木。葉の紅葉も意外ときれいです。",
    doneText: "実がなった！",
    appeal: "秋の味覚の代表。食べられる実がたくさん収穫でき、秋の紅葉も美しい、暮らしに近い果樹です。",
  },
  {
    name: "イロハモミジ", animal: "赤トンボ", type: "foliage",
    bloomColor: ["#e05a3a", "#f6b89e"],
    evergreen: false, height: "tall",
    hintLeaf: "手のひらの形に深く切れこむ葉っぱ",
    hintBloom: "葉っぱが赤く染まりそうな気配…",
    seasonMonths: [11],
    matureDesc: "秋に手のひらの形の葉が真っ赤に染まる、紅葉の主役。春の新緑もやわらかくてきれいです。",
    doneText: "紅葉した！",
    appeal: "新緑、花、紅葉と四季折々の美しさを楽しめる紅葉の主役。シンボルツリーとしても人気です。",
  },
  {
    name: "ユズ", animal: "カピバラ", type: "fruit",
    bloomColor: ["#f2d03b", "#faf0c0"],
    evergreen: true, height: "medium",
    hintLeaf: "葉の柄に翼がある革質の葉っぱ。ちぎるといい香り…？",
    hintBloom: "黄色い実がなりそうな気配…",
    seasonMonths: [12],
    matureDesc: "実の皮がとてもよい香りで、料理の香りづけに大活躍。冬至の日にお風呂に浮かべる習慣でも有名です。",
    doneText: "実がなった！",
    appeal: "独特の香りの果皮が魅力。冬至のユズ湯としておなじみの、香りで楽しむ冬の果樹です。",
  },
  {
    name: "ゴールドクレスト", animal: "ヒヨコ", type: "foliage",
    bloomColor: ["#cdd96a", "#eef3c4"],
    evergreen: true, height: "medium",
    hintLeaf: "やわらかい黄緑の、うろこのような葉っぱ",
    hintBloom: "黄金色にかがやきそうな気配…",
    seasonMonths: [12],
    matureDesc: "黄金色にかがやく明るい葉が、庭をぱっと明るくするコニファー。クリスマスツリーとしても人気です。",
    doneText: "見ごろになった！",
    appeal: "輝くような明るい葉色が庭をぱっと明るくするコニファー。葉にはさわやかな香りがあります。",
  },
];

const GAME_CONFIG = {
  tapsPerStage: 10,
  tapsToComplete: 50,
  storageKey: "sodatetePA_v1",
};
